In [1]:
import pandas as pd
import numpy as np

In [2]:
dt1 = pd.read_csv('final2.csv', index_col=0)
dt2 = pd.read_csv('final_cof_bean_pork.csv', index_col=0)
dt = pd.merge(dt1, dt2, left_index=True, right_index=True, how='left')
dt.set_index(keys='date_x', inplace=True)

In [3]:
dt3 = pd.read_csv('cof_10month.csv', index_col='date')
dt4 = pd.read_csv('cu_wti_gas_koreastock_10month.csv', index_col='date')
dt3.drop(['Unnamed: 0'], axis=1, inplace=True)
dt3.reset_index()
dt4.reset_index()
dt5 = pd.merge(dt3, dt4, left_index=True, right_index=True, how='left')

In [4]:
dt5.info() # bn_vol 결측치가 너무 많음 -> test상 사용이 불가능하므로 모두 제거

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 2022- 10- 31 to 2022- 10- 03
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cof_cost        21 non-null     float64
 1   cof_vol         21 non-null     int64
 2   bn_cost         21 non-null     float64
 3   bn_vol          2 non-null      float64
 4   pk_cost         21 non-null     float64
 5   pk_vol          21 non-null     int64
 6   wheat_cost      21 non-null     float64
 7   wheat_vol       21 non-null     int64
 8   al_cost         21 non-null     float64
 9   al_vol          21 non-null     int64
 10  Unnamed: 0      21 non-null     int64
 11  cu_cost         21 non-null     float64
 12  oil_cost        21 non-null     float64
 13  oil_vol         21 non-null     float64
 14  gas_cost        21 non-null     float64
 15  kosdaq_cost     19 non-null     float64
 16  kosdaq100_cost  19 non-null     float64
 17  kospi_cost      19 non-null     float64
 18  kospi200_cost   19 non-null     float64
 19  gas_vol         21 non-null     float64
 20  cu_vol          21 non-null     float64
dtypes: float64(16), int64(5)
memory usage: 4.2+ KB

In [5]:
dt5.sort_values('date', inplace=True)

In [6]:
dt5

,cof_cost,cof_vol,bn_cost,bn_vol,pk_cost,pk_vol,wheat_cost,wheat_vol,al_cost,al_vol,...,cu_cost,oil_cost,oil_vol,gas_cost,kosdaq_cost,kosdaq100_cost,kospi_cost,kospi200_cost,gas_vol,cu_vol
date,,,,,,,,,,,,,,,,,,,,,
2022- 10- 03,215.75,22480,1373.12,NaN,88.78,5080,912.00,52400,2219.5,51200,...,3.4100,82.70,135990.0,6.470,NaN,NaN,NaN,NaN,104480.0,49580.0
2022- 10- 04,219.30,20040,1383.50,NaN,87.00,9620,903.00,50520,2348.0,66170,...,3.4900,85.50,156000.0,6.837,696.79,1391.62,2209.38,288.27,121680.0,76840.0
2022- 10- 05,224.65,23920,1369.75,NaN,90.80,9870,902.00,39960,2352.0,53310,...,3.5005,86.84,160030.0,6.930,685.34,1360.93,2215.22,289.05,80870.0,59970.0
2022- 10- 06,217.70,22410,1358.00,NaN,92.38,5880,879.00,46420,2347.0,46800,...,3.4460,87.59,108490.0,6.972,706.01,1402.82,2237.86,291.26,109940.0,67870.0
2022- 10- 07,218.10,21180,1367.00,NaN,92.95,4870,880.25,38140,2299.0,34590,...,3.3865,91.35,242270.0,6.748,698.49,1377.72,2232.84,290.41,124710.0,53150.0
2022- 10- 10,217.45,11670,1374.00,NaN,93.75,4100,938.00,77240,2260.0,35040,...,3.4305,89.84,156090.0,6.435,NaN,NaN,NaN,NaN,114240.0,58570.0
2022- 10- 11,217.85,15730,1376.25,NaN,93.03,2940,901.00,65150,2236.0,44160,...,3.4620,87.97,187520.0,6.596,669.50,1328.80,2192.07,284.96,106890.0,60600.0
2022- 10- 12,209.75,31780,1395.50,NaN,93.10,2230,882.25,44740,2305.0,42530,...,3.4250,86.06,211340.0,6.435,671.67,1342.65,2202.47,287.09,112380.0,56580.0
2022- 10- 13,202.15,34570,1395.75,NaN,93.42,2580,892.25,63570,2359.5,71880,...,3.4405,87.95,185660.0,6.741,651.59,1315.17,2162.87,282.57,131390.0,85970.0
2022- 10- 14,196.70,31210,1383.75,NaN,93.38,750,859.75,45070,2306.0,35860,...,3.4235,85.61,237030.0,6.453,678.24,1374.07,2212.55,289.36,96730.0,70500.0
2022- 10- 17,195.55,21870,1385.25,NaN,84.95,27110,861.00,42650,2229.0,42210,...,3.4155,85.46,172020.0,5.999,682.00,1376.70,2219.71,289.57,132420.0,56830.0
2022- 10- 18,195.10,18450,1372.00,143270.0,86.47,27230,849.50,46280,2193.0,58180,...,3.3620,82.82,97300.0,5.745,697.09,1407.34,2249.95,293.59,102090.0,72590.0
2022- 10- 19,192.30,19270,1372.50,NaN,87.38,21750,841.25,39810,2170.5,39280,...,3.3180,85.55,71310.0,5.462,690.56,1389.67,2237.44,291.29,107160.0,65740.0
2022- 10- 20,191.05,20020,1389.50,NaN,87.03,15120,849.25,34080,2209.5,39800,...,3.4105,85.98,18180.0,5.358,680.44,1359.58,2218.09,288.61,104220.0,77240.0
2022- 10- 21,190.90,17810,1395.50,NaN,89.12,23940,850.75,41910,2206.0,31460,...,3.4745,85.05,272800.0,4.959,674.48,1356.36,2213.12,288.57,101730.0,84800.0
2022- 10- 24,190.40,18490,1372.00,NaN,87.92,26650,838.75,38010,2175.0,31670,...,3.4305,84.58,250730.0,5.199,688.50,1394.23,2236.16,291.47,69670.0,70070.0
2022- 10- 25,185.80,28940,1382.00,98750.0,88.45,25860,834.75,40780,2215.0,40190,...,3.3970,85.32,240440.0,5.613,688.85,1389.44,2235.07,291.58,39950.0,60020.0
2022- 10- 26,179.75,25200,1381.75,NaN,88.50,23370,840.50,39250,2335.0,56820,...,3.5450,87.91,287180.0,5.606,683.17,1382.87,2249.56,293.85,36780.0,97900.0
2022- 10- 27,178.85,19570,1382.25,NaN,85.12,30200,838.50,36090,2287.5,46130,...,3.5195,89.08,292560.0,5.186,695.09,1415.23,2288.78,298.82,1730.0,82340.0
2022- 10- 28,169.80,30550,1387.75,NaN,86.10,22530,829.25,33950,2211.5,44840,...,3.4290,87.90,263400.0,5.684,687.63,1399.85,2268.40,295.06,84710.0,73930.0
2022- 10- 31,177.70,26370,1419.50,NaN,84.92,25450,882.25,98980,2222.0,39310,...,3.3750,86.53,285340.0,6.355,695.33,1416.59,2293.61,299.58,128750.0,66570.0

In [7]:
dt.drop(['kospi_vol', 'kospi200_vol', 'kosdaq_vol','kosdaq100_vol'], axis=1, inplace = True)
dt5.drop(['Unnamed: 0'],axis=1, inplace = True)

In [8]:
dt_proc = dt.drop(['kospi_cost', 'kospi200_cost', 'kosdaq_cost','kosdaq100_cost', 'date_y'], axis=1)
dt_proc2 = dt5.drop(['kospi_cost', 'kospi200_cost', 'kosdaq_cost','kosdaq100_cost'], axis=1)

In [9]:
dt_proc = dt_proc.interpolate()
dt_proc2 = dt_proc2.interpolate()
dt_proc.sort_values('date_x', inplace=True)

In [10]:
dt_proc = pd.concat([dt_proc, dt_proc2], axis=0)

In [11]:
dt = dt_proc

In [12]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1270 entries, 2018- 01- 02 to 2022- 10- 31
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cu_cost     1270 non-null   float64
 1   oil_cost    1270 non-null   float64
 2   gas_cost    1270 non-null   float64
 3   wheat_cost  1270 non-null   float64
 4   al_cost     1270 non-null   float64
 5   cu_vol      1270 non-null   float64
 6   wheat_vol   1270 non-null   float64
 7   gas_vol     1270 non-null   float64
 8   oil_vol     1270 non-null   float64
 9   al_vol      1270 non-null   float64
 10  cof_cost    1270 non-null   float64
 11  bn_cost     1270 non-null   float64
 12  pk_cost     1270 non-null   float64
 13  cof_vol     1270 non-null   float64
 14  bn_vol      1258 non-null   float64
 15  pk_vol      1270 non-null   float64
dtypes: float64(16)
memory usage: 168.7+ KB

In [13]:
dt['cu_rol7'] = dt['cu_cost'].rolling(window=7).mean()
dt['cu_rol30'] = dt['cu_cost'].rolling(window=30).mean()
dt['cu_rol7_c1'] = dt['cu_rol7'].diff()
dt['cu_rol30_c1'] = dt['cu_rol30'].diff()

dt['oil_rol7'] = dt['oil_cost'].rolling(window=7).mean()
dt['oil_rol30'] = dt['oil_cost'].rolling(window=30).mean()
dt['oil_rol7_c1'] = dt['oil_rol7'].diff()
dt['oil_rol30_c1'] = dt['oil_rol30'].diff()

dt['gas_rol7'] = dt['gas_cost'].rolling(window=7).mean()
dt['gas_rol30'] = dt['gas_cost'].rolling(window=30).mean()
dt['gas_rol7_c1'] = dt['gas_rol7'].diff()
dt['gas_rol30_c1'] = dt['gas_rol30'].diff()

dt['al_rol7'] = dt['al_cost'].rolling(window=7).mean()
dt['al_rol30'] = dt['al_cost'].rolling(window=30).mean()
dt['al_rol7_c1'] = dt['al_rol7'].diff()
dt['al_rol30_c1'] = dt['al_rol30'].diff()

dt['wheat_rol7'] = dt['wheat_cost'].rolling(window=7).mean()
dt['wheat_rol30'] = dt['wheat_cost'].rolling(window=30).mean()
dt['wheat_rol7_c1'] = dt['wheat_rol7'].diff()
dt['wheat_rol30_c1'] = dt['wheat_rol30'].diff()

dt['cof_rol7'] = dt['cof_cost'].rolling(window=7).mean()
dt['cof_rol30'] = dt['cof_cost'].rolling(window=30).mean()
dt['cof_rol7_c1'] = dt['cof_rol7'].diff()
dt['cof_rol30_c1'] = dt['cof_rol30'].diff()

dt['pk_rol7'] = dt['pk_cost'].rolling(window=7).mean()
dt['pk_rol30'] = dt['pk_cost'].rolling(window=30).mean()
dt['pk_rol7_c1'] = dt['pk_rol7'].diff()
dt['pk_rol30_c1'] = dt['pk_rol30'].diff()

dt['bn_rol7'] = dt['bn_cost'].rolling(window=7).mean()
dt['bn_rol30'] = dt['bn_cost'].rolling(window=30).mean()
dt['bn_rol7_c1'] = dt['bn_rol7'].diff()
dt['bn_rol30_c1'] = dt['bn_rol30'].diff()

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler_ = MinMaxScaler()
scaled_oil = scaler_.fit_transform(dt[['oil_vol']])
dt['scaled_oil'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['cu_vol']])
dt['scaled_cu'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['gas_vol']])
dt['scaled_gas'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['wheat_vol']])
dt['scaled_wheat'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['pk_vol']])
dt['scaled_pk'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['al_vol']])
dt['scaled_al'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['cof_vol']])
dt['scaled_cof'] = scaled_oil

scaled_oil = scaler_.fit_transform(dt[['bn_vol']])
dt['scaled_bn'] = scaled_oil

In [15]:

dt.iloc[-21:, :]

,cu_cost,oil_cost,gas_cost,wheat_cost,al_cost,cu_vol,wheat_vol,gas_vol,oil_vol,al_vol,...,bn_rol7_c1,bn_rol30_c1,scaled_oil,scaled_cu,scaled_gas,scaled_wheat,scaled_pk,scaled_al,scaled_cof,scaled_bn
2022- 10- 03,3.4100,82.70,6.470,912.00,2219.5,49580.0,52400.0,104480.0,135990.0,51200.0,...,-11.411429,-1.029333,0.368118,0.215431,0.225502,0.314469,0.097484,0.061223,0.308114,NaN
2022- 10- 04,3.4900,85.50,6.837,903.00,2348.0,76840.0,50520.0,121680.0,156000.0,66170.0,...,-6.035714,-1.725000,0.422284,0.333927,0.263057,0.303187,0.187438,0.079524,0.274671,NaN
2022- 10- 05,3.5005,86.84,6.930,902.00,2352.0,59970.0,39960.0,80870.0,160030.0,53310.0,...,-5.857143,-3.012333,0.433193,0.260596,0.173952,0.239813,0.192392,0.063803,0.327851,NaN
2022- 10- 06,3.4460,87.59,6.972,879.00,2347.0,67870.0,46420.0,109940.0,108490.0,46800.0,...,-7.142857,-3.300000,0.293677,0.294936,0.237424,0.278581,0.113335,0.055844,0.307155,NaN
2022- 10- 07,3.3865,91.35,6.748,880.25,2299.0,53150.0,38140.0,124710.0,242270.0,34590.0,...,-5.964286,-2.141667,0.655812,0.230950,0.269672,0.228890,0.093323,0.040917,0.290296,NaN
2022- 10- 10,3.4305,89.84,6.435,938.00,2260.0,58570.0,77240.0,114240.0,156090.0,35040.0,...,-5.250000,-2.908333,0.422527,0.254510,0.246812,0.463542,0.078066,0.041467,0.159951,NaN
2022- 10- 11,3.4620,87.97,6.596,901.00,2236.0,60600.0,65150.0,106890.0,187520.0,44160.0,...,1.642857,-2.050000,0.507607,0.263334,0.230764,0.390986,0.055082,0.052617,0.215598,NaN
2022- 10- 12,3.4250,86.06,6.435,882.25,2305.0,56580.0,44740.0,112380.0,211340.0,42530.0,...,3.197143,-1.233333,0.572086,0.245860,0.242751,0.268499,0.041014,0.050624,0.435581,NaN
2022- 10- 13,3.4405,87.95,6.741,892.25,2359.5,85970.0,63570.0,131390.0,185660.0,71880.0,...,1.750000,-0.891667,0.502572,0.373614,0.284258,0.381504,0.047949,0.086505,0.473821,NaN
2022- 10- 14,3.4235,85.61,6.453,859.75,2306.0,70500.0,45070.0,96730.0,237030.0,35860.0,...,2.000000,-0.291667,0.641627,0.306368,0.208581,0.270480,0.011690,0.042470,0.427769,NaN
2022- 10- 17,3.4155,85.46,5.999,861.00,2229.0,56830.0,42650.0,132420.0,172020.0,42210.0,...,3.892857,-1.175000,0.465649,0.246946,0.286507,0.255956,0.533981,0.050233,0.299753,NaN
2022- 10- 18,3.3620,82.82,5.745,849.50,2193.0,72590.0,46280.0,102090.0,97300.0,58180.0,...,0.714286,-0.891667,0.263386,0.315453,0.220284,0.277741,0.536358,0.069756,0.252878,0.406486
2022- 10- 19,3.3180,85.55,5.462,841.25,2170.5,65740.0,39810.0,107160.0,71310.0,39280.0,...,-0.214286,-0.366667,0.193032,0.285677,0.231354,0.238913,0.427779,0.046651,0.264117,0.381223
2022- 10- 20,3.4105,85.98,5.358,849.25,2209.5,77240.0,34080.0,104220.0,18180.0,39800.0,...,1.892857,0.116667,0.049212,0.335666,0.224934,0.204525,0.296414,0.047287,0.274397,0.355961
2022- 10- 21,3.4745,85.05,4.959,850.75,2206.0,84800.0,41910.0,101730.0,272800.0,31460.0,...,0.000000,-0.558333,0.738455,0.368529,0.219498,0.251515,0.471171,0.037091,0.244106,0.330699
2022- 10- 24,3.4305,84.58,5.199,838.75,2175.0,70070.0,38010.0,69670.0,250730.0,31670.0,...,-3.392857,-3.875000,0.678713,0.304499,0.149498,0.228110,0.524866,0.037348,0.253427,0.305436
2022- 10- 25,3.3970,85.32,5.613,834.75,2215.0,60020.0,40780.0,39950.0,240440.0,40190.0,...,-0.250000,-3.225000,0.650858,0.260813,0.084607,0.244734,0.509213,0.047763,0.396656,0.280174
2022- 10- 26,3.5450,87.91,5.606,840.50,2335.0,97900.0,39250.0,36780.0,287180.0,56820.0,...,-0.500000,-2.441667,0.777381,0.425473,0.077686,0.235552,0.459877,0.068094,0.345395,0.280174
2022- 10- 27,3.5195,89.08,5.186,838.50,2287.5,82340.0,36090.0,1730.0,292560.0,46130.0,...,1.464286,-2.308333,0.791944,0.357835,0.001157,0.216588,0.595205,0.055025,0.268229,0.280174
2022- 10- 28,3.4290,87.90,5.684,829.25,2211.5,73930.0,33950.0,84710.0,263400.0,44840.0,...,2.178571,-2.025000,0.713010,0.321278,0.182336,0.203745,0.443234,0.053448,0.418723,0.280174
2022- 10- 31,3.3750,86.53,6.355,882.25,2222.0,66570.0,98980.0,128750.0,285340.0,39310.0,...,4.285714,-1.391667,0.772400,0.289285,0.278493,0.594011,0.501090,0.046688,0.361431,0.280174

In [16]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1270 entries, 2018- 01- 02 to 2022- 10- 31
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cu_cost         1270 non-null   float64
 1   oil_cost        1270 non-null   float64
 2   gas_cost        1270 non-null   float64
 3   wheat_cost      1270 non-null   float64
 4   al_cost         1270 non-null   float64
 5   cu_vol          1270 non-null   float64
 6   wheat_vol       1270 non-null   float64
 7   gas_vol         1270 non-null   float64
 8   oil_vol         1270 non-null   float64
 9   al_vol          1270 non-null   float64
 10  cof_cost        1270 non-null   float64
 11  bn_cost         1270 non-null   float64
 12  pk_cost         1270 non-null   float64
 13  cof_vol         1270 non-null   float64
 14  bn_vol          1258 non-null   float64
 15  pk_vol          1270 non-null   float64
 16  cu_rol7         1264 non-null   float64
 17  cu_rol30        1241 non-null   float64
 18  cu_rol7_c1      1263 non-null   float64
 19  cu_rol30_c1     1240 non-null   float64
 20  oil_rol7        1264 non-null   float64
 21  oil_rol30       1241 non-null   float64
 22  oil_rol7_c1     1263 non-null   float64
 23  oil_rol30_c1    1240 non-null   float64
 24  gas_rol7        1264 non-null   float64
 25  gas_rol30       1241 non-null   float64
 26  gas_rol7_c1     1263 non-null   float64
 27  gas_rol30_c1    1240 non-null   float64
 28  al_rol7         1264 non-null   float64
 29  al_rol30        1241 non-null   float64
 30  al_rol7_c1      1263 non-null   float64
 31  al_rol30_c1     1240 non-null   float64
 32  wheat_rol7      1264 non-null   float64
 33  wheat_rol30     1241 non-null   float64
 34  wheat_rol7_c1   1263 non-null   float64
 35  wheat_rol30_c1  1240 non-null   float64
 36  cof_rol7        1264 non-null   float64
 37  cof_rol30       1241 non-null   float64
 38  cof_rol7_c1     1263 non-null   float64
 39  cof_rol30_c1    1240 non-null   float64
 40  pk_rol7         1264 non-null   float64
 41  pk_rol30        1241 non-null   float64
 42  pk_rol7_c1      1263 non-null   float64
 43  pk_rol30_c1     1240 non-null   float64
 44  bn_rol7         1264 non-null   float64
 45  bn_rol30        1241 non-null   float64
 46  bn_rol7_c1      1263 non-null   float64
 47  bn_rol30_c1     1240 non-null   float64
 48  scaled_oil      1270 non-null   float64
 49  scaled_cu       1270 non-null   float64
 50  scaled_gas      1270 non-null   float64
 51  scaled_wheat    1270 non-null   float64
 52  scaled_pk       1270 non-null   float64
 53  scaled_al       1270 non-null   float64
 54  scaled_cof      1270 non-null   float64
 55  scaled_bn       1258 non-null   float64
dtypes: float64(56)
memory usage: 565.5+ KB

In [17]:
dt_7 = dt.iloc[:,[18, 22, 26, 30, 34, 38, 42, 46, 48, 49, 50, 51, 52, 53, 54, 55]]
dt_30 = dt.iloc[:, [19, 23, 27, 31, 35, 38, 43, 47, 48, 49, 50, 51, 52, 53, 54, 55]]

In [18]:

dt_7

,cu_rol7_c1,oil_rol7_c1,gas_rol7_c1,al_rol7_c1,wheat_rol7_c1,cof_rol7_c1,pk_rol7_c1,bn_rol7_c1,scaled_oil,scaled_cu,scaled_gas,scaled_wheat,scaled_pk,scaled_al,scaled_cof,scaled_bn
2018- 01- 02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000298,0.466290,0.696463,0.428194,0.379433,0.060392,0.111020,0.008228
2018- 01- 03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000027,0.453293,0.586659,0.425914,0.379433,0.048839,0.111020,0.008228
2018- 01- 04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000081,0.458248,0.695437,0.352458,0.379433,0.042519,0.111020,0.008228
2018- 01- 05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.369181,0.501638,0.375383,0.379433,0.037054,0.111020,0.008228
2018- 01- 08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.802826,0.381569,0.495721,0.431015,0.379433,0.060013,0.111020,0.008228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022- 10- 25,-0.003786,-0.041429,-0.120000,-13.000000,-3.571429,-1.557143,-0.704286,-0.250000,0.650858,0.260813,0.084607,0.244734,0.509213,0.047763,0.396656,0.280174
2022- 10- 26,0.018500,0.350000,-0.056143,15.142857,-2.928571,-2.257143,0.507143,-0.500000,0.777381,0.425473,0.077686,0.235552,0.459877,0.068094,0.345395,0.280174
2022- 10- 27,0.022500,0.894286,-0.079857,13.500000,-1.571429,-2.321429,-0.192857,1.464286,0.791944,0.357835,0.001157,0.216588,0.595205,0.055025,0.268229,0.280174
2022- 10- 28,0.015857,0.335714,0.031714,5.857143,-1.714286,-3.214286,-0.182857,2.178571,0.713010,0.321278,0.182336,0.203745,0.443234,0.053448,0.418723,0.280174
2022- 10- 31,-0.005071,0.078571,0.142429,1.785714,4.714286,-1.907143,-0.301429,4.285714,0.772400,0.289285,0.278493,0.594011,0.501090,0.046688,0.361431,0.280174

In [19]:
dt1 = pd.read_csv('final2.csv', index_col=0)
dt2 = pd.read_csv('final_cof_bean_pork.csv', index_col=0)
org = pd.merge(dt1, dt2, left_index=True, right_index=True, how='left')
org.set_index(keys='date_x', inplace=True)
org = pd.concat([org, dt5], axis=0)

In [20]:
dt_7_Y = pd.merge(dt_7, org['kospi_cost'], left_index=True, right_index=True, how='left')
dt_30_Y = pd.merge(dt_30, org['kospi_cost'], left_index=True, right_index=True, how='left')
dt_7_Y = pd.merge(dt_7_Y, org['kospi200_cost'], left_index=True, right_index=True, how='left')
dt_30_Y = pd.merge(dt_30_Y, org['kospi200_cost'], left_index=True, right_index=True, how='left')
dt_7_Y = pd.merge(dt_7_Y, org['kosdaq_cost'], left_index=True, right_index=True, how='left')
dt_30_Y = pd.merge(dt_30_Y, org['kosdaq_cost'], left_index=True, right_index=True, how='left')
dt_7_Y = pd.merge(dt_7_Y, org['kosdaq100_cost'], left_index=True, right_index=True, how='left')
dt_30_Y = pd.merge(dt_30_Y, org['kosdaq100_cost'], left_index=True, right_index=True, how='left')

In [24]:
dt_7_Y.drop(['scaled_bn'], axis=1, inplace=True)
dt_30_Y.drop(['scaled_bn'], axis=1, inplace=True)


dt_7_Y = dt_7_Y.dropna(axis=0)
dt_30_Y = dt_30_Y.dropna(axis=0)

In [25]:
dt_7_Y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1175 entries, 2018- 01- 11 to 2022- 10- 31
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cu_rol7_c1      1175 non-null   float64
 1   oil_rol7_c1     1175 non-null   float64
 2   gas_rol7_c1     1175 non-null   float64
 3   al_rol7_c1      1175 non-null   float64
 4   wheat_rol7_c1   1175 non-null   float64
 5   cof_rol7_c1     1175 non-null   float64
 6   pk_rol7_c1      1175 non-null   float64
 7   bn_rol7_c1      1175 non-null   float64
 8   scaled_oil      1175 non-null   float64
 9   scaled_cu       1175 non-null   float64
 10  scaled_gas      1175 non-null   float64
 11  scaled_wheat    1175 non-null   float64
 12  scaled_pk       1175 non-null   float64
 13  scaled_al       1175 non-null   float64
 14  scaled_cof      1175 non-null   float64
 15  kospi_cost      1175 non-null   float64
 16  kospi200_cost   1175 non-null   float64
 17  kosdaq_cost     1175 non-null   float64
 18  kosdaq100_cost  1175 non-null   float64
dtypes: float64(19)
memory usage: 183.6+ KB

In [26]:
dt_30_Y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1152 entries, 2018- 02- 14 to 2022- 10- 31
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cu_rol30_c1     1152 non-null   float64
 1   oil_rol30_c1    1152 non-null   float64
 2   gas_rol30_c1    1152 non-null   float64
 3   al_rol30_c1     1152 non-null   float64
 4   wheat_rol30_c1  1152 non-null   float64
 5   cof_rol7_c1     1152 non-null   float64
 6   pk_rol30_c1     1152 non-null   float64
 7   bn_rol30_c1     1152 non-null   float64
 8   scaled_oil      1152 non-null   float64
 9   scaled_cu       1152 non-null   float64
 10  scaled_gas      1152 non-null   float64
 11  scaled_wheat    1152 non-null   float64
 12  scaled_pk       1152 non-null   float64
 13  scaled_al       1152 non-null   float64
 14  scaled_cof      1152 non-null   float64
 15  kospi_cost      1152 non-null   float64
 16  kospi200_cost   1152 non-null   float64
 17  kosdaq_cost     1152 non-null   float64
 18  kosdaq100_cost  1152 non-null   float64
dtypes: float64(19)
memory usage: 180.0+ KB

In [27]:
dt_7_Y.to_csv('rol7+4Y.csv')
dt_30_Y.to_csv('rol30+4Y.csv')

In [ ]:
dt_7_Y